### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by kkoci** [odoo-chile/l10n_cl_invoice#17]
Buenas noches, acabo de actualizar éste módulo y el dte, antes de probar el dte, instalo éste ya que es una dependencia, pero me arroja éste error:

`

Odoo Server Error

Traceback (most recent call last):
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 683, in dispatch
    result = self._call_function(*_self.params)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 312, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 962, in __call__
    return self.method(_args, *_kw)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 512, in response_wrap
    response = f(_args, *_kw)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 137, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/module.py", line 293, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/models.py", line 2637, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/models.py", line 2393, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/fields.py", line 82, in <lambda>
    return api.model(lambda model: field.convert_to_write(value(model)))
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/fields.py", line 1712, in convert_to_write
    return value.id
AttributeError: 'NoneType' object has no attribute 'id'

`

Me parece muy extraño, el anterior si se instalaba sin problemas, pero resulta que el dte está actualizado y éste también, así que supongo que habrá que ver ésto antes de instalar el de facturación electrónica.

Bueno, muchas gracias, a ver qué pueda ser, o si es reproducible en su instancia.

Un saludo.

**Comment by dansanti** [comment]
Has actualizado la carpeta con nuevos archivos?, si es asi, deber primero que todo reiniciar el servidor odoo sudo service odoo restart   y luego presionar en upgrate, en el modulo invoice

**Comment by kkoci** [comment]
Hola @dansanti Gracias por tu respuesta, no, simplemente, saqué la anterior y la sustituí con ésta, aunque están en otro path que yo le paso cuando inicio el servidor, déjame ver si lo cambio y veo qué pasa.

**Comment by kkoci** [comment]
Lo que había pasado es que había dejado el otro módulo con el mismo nombre en otra carpeta, ahora me dá otro error, bueno, cualquier cosa abro otro issue, Muchas Gracias
