### ISSUE TITLE
journal_activities_ids dominio no está correcto del todo

### ISSUE THREAD

**Issue by dansanti** [odoo-chile/l10n_cl_invoice#9]
Hola!

he estado tratando de resolver el siguiente problema:

en la línea 37  del archivo journal_view.xml se encuentra :
`xml 
domain="[('partner_ids', '=', company_id)]"/>
`

Inicialmente funciona bien, porque se dan las coincidencias de que el company_id == partner_id && partner_ids.length == 1
- En el caso de que se tenga multicompañia, y las 2 compañías coincidan en las mismas actividades se genera un listado y no un entero para poder aplicar la igualdad.
- En el caso de que se cree más de una compañía, el icompany_id no necesariamente es igual al partner_id, por lo que no se cumple 'partner_ids', '=', company_id , ya que partner_ids almacena el id de partner , no el de compañia

**Comment by Danisan** [comment]
quizá una solución sería algo como 
[('company_id', 'in', 'partner_ids')]

Habria que probar

**Comment by Danisan** [comment]
Yo tomé para otro lado las prioridades ahora, mientras así sirve.. pero si.. dejo abierto este issue para probar como se arregla.

**Comment by Cu4rach4** [comment]
Hola...asumo que este es el error!

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 581, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 810, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 410, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 753, in _tag_record
    f_val = _eval_xml(self,field, self.pool, cr, self.uid, self.idref)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 173, in _eval_xml
    for n in node]), idref)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 162, in _process
    idref[id] = self.id_get(cr, id)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 828, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 839, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 909, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 899, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: l10n_cl_invoice.action_account_journal_document_config_form" while parsing /home/ubuntu/odoo-bmya-cl/l10n_cl_invoice/views/journal_view.xml:16, near
<record id="view_account_journal_cl_form" model="ir.ui.view">
            <field name="model">account.journal</field>
            <field name="name">account.journal.ar.form</field>
            <field name="inherit_id" ref="account.view_account_journal_form"/>
            <field name="arch" type="xml">
                <data><field name="type" position="after">
                    <field name="use_documents" attrs="{'invisible': [('type','not in',['purchase','sale','purchase_refund','sale_refund'])]}"/>
                </field>

```
            <notebook position="inside">
                <page string="Documents" attrs="{'invisible': ['|',('use_documents','=',False),('type','not in',['purchase','sale','purchase_refund','sale_refund'])]}">
                    <button name="%(action_account_journal_document_config_form)d" string="Create Journal Documents" type="action" context="{'type':type, 'excempt_documents': excempt_documents}"/>
                    <group>
                        <field name="point_of_sale_id" attrs="{'invisible': ['|',('type','not in',['sale','sale_refund'])],'required': [('use_documents','=',True),('type','in',['sale','sale_refund'])]}" context="{'default_company_id':company_id}"/>
                        <field name="point_of_sale" attrs="{'invisible': ['|',('type','not in',['sale','sale_refund'])]}"/>
                        <field name="journal_activities_ids" attrs="{'invisible': ['|',('type','not in',['purchase','sale','purchase_refund','sale_refund'])],'required': [('use_documents','=',True),('type','in',['sale','sale_refund'])]}" context="{'default_company_id':company_id}" placeholder="Giros del Diario" widget="many2many_tags" options="{'no_create': True}" domain="[('partner_ids', '=', company_id)]"/>
                        <field name="excempt_documents" readonly="True"/>
                        <!--attrs="{'readonly': [('type', 'like', 'sale')]}"-->
                    </group>
                    <field name="journal_document_class_ids" context="{'journal_type':type}"/>
                </page>
            </notebook>
        </data></field>
    </record>`
```

O corresponde a otro, entiendo que es un problema de xml, pero no logro encontrar el error...gracias

**Comment by dansanti** [comment]
No , eso es por error de dependencia, el error que planteo es de dominio, y ocurre cuando tienes multiempresa

**Comment by dansanti** [comment]
si usas odoo 9 verifica de que has clonado el branch 9.0

**Comment by Cu4rach4** [comment]
Hola Daniel,

Las dependencias ya las instale, encontré los módulos faltantes, y estoy usando la versión 8, para no tener problemas...podría volver a instalar los módulos ya que dieron algunos problemas sclmo tu bien indicas de dependencias...te avisaré nuevamente
